# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'test' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '8.0'

use_frameworks!

pod 'Alamofire', '~> 3.0.0'
pod 'SwiftyJSON', '~> 2.3.0'
end

target 'testTests' do

end

target 'testUITests' do

end

