source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SwiftyCompanion' do
    pod 'Alamofire', '~> 3.0'
    pod 'SwiftyJSON'
end

target 'SwiftyCompanionTests' do

end

target 'SwiftyCompanionUITests' do

end

